### ISSUE TITLE
Emphasize difference to visual mode

### ISSUE THREAD

**Issue by kiryph** [00sapo/visual.nvim#2]
Quote from [Readme.md](https://github.com/00sapo/visual.nvim/blob/main/Readme.md):

> In visual.nvim (and Helix), this actually becomes `-3w3wd`, with the `-` used for "extending" selections.

Standard vim visual mode `v3w3wd` would do the same.

Can the [Readme.md](https://github.com/00sapo/visual.nvim/blob/main/Readme.md) show an example where the difference to visual mode becomes apparent?

**Comment by 00sapo** [comment]
Currently, instead of vwd, you just need wd (or ed for the current word). 

Due to the option format, even 3wd only works with -3wd. I just have to fix the option format to make only parts of the commands repeatable. After this, to delete n words, you just do 3wd, and you will use - only when you see you have typed a wrong text object. Even the way in which w and b work will be improved: as of now, they select the next (or previous) word, but they should first select the current word imho. I'm not completely sure of this, let's talk!

Other differences:
* Instead of viw, you can do iw.
* From visual mode, you can do many things without leaving it, see e.g. R,S, A, I.
* You can add/change/remove surrounding chars with just two commands, and directly see what you're going to change (sa, sc, sd). N.B. this feature still broken as of now.
* You see the selected region, or text object. This is the most important thing. In your example, in vim you would probably do c3w, then u, then c6w, then u, etc. Here, you will do 3w-3wwc. Likely, it will need even less commands, because you are seeing what you are doing. This is much less stressful and less distracting,once you get used.
* Trust me, I tried for years forcing me using v before the command typed. It's not the same just because most of the time you _think_ of knowing the correct command and realize it was wrong only afterwards. The only solution is being _always_ in visual mode before of typing the command.

Things to be improved:
* Support undo changes as unique blocks for each command
* Support macros (I don't have many ideas about this, still need to explore)
* Some user asked for supporting vim-visual-multi
* Selection history: if you select something wrong, you can go back with L and H
* Better keymaps (this need your testing and suggestions, people!)
* Documentation and snippet configuration for nvchad, lunarvim, astronvim, lazy I'm, Kickstarter, clean nvim (this will likely come after Undo, macro, and history)

Things to fix:
* Option format
* Surround commands on line extremes

**Comment by kiryph** [comment]
Thanks for your detailed answer. Much appreciated.

> Currently, instead of vwd, you just need wd (or ed for the current word).

> - Instead of viw, you can do iw.

I see.

> - You see the selected region, or text object. This is the most important thing. In your example, in vim you would probably do `c3w`, then `u`, then `c6w`, then `u`, etc. Here, you will do `3w-3wwc`.

This helped me to understand the purpose of `-` better.

Can the first paragraph of the Readme.md be slightly modified along the lines as following?

> visual.nvim reverses the order of operator and motion/text object to motion(s)/text object and then operator, similar to the text editors Kakoune and Helix. Since the target specified by a motion or text object might be refined the reverse order is more user friendly. Here is an example: 
> 
> In nvim, you do c3w. Ah no! It was wrong, let's retry: uc5w... wooops! Sorry, it is still wrong: uc6w!
>
> In visual.nvim, this actually becomes `3w-2wwd, with `-` used for "extending/refining" selections.

This is only a draft. But the use of `-` was not immediately clear to to me. It could also be mentioned that overshooting can also be corrected.

---

> Trust me, I tried for years forcing me using `v` before the command typed. It's not the same just because most of the time you think of knowing the correct command and realize it was wrong only afterwards. The only solution is being always in visual mode before of typing the command.

I believe you. This is the reason why I use counts only if it is obvious, e.g. delete 2 lines. Enabling relative line numbers helps for line wise operations. Otherwise I actually use visual mode with repeated pressing of `w` or other motions which is not really precise. Sticking to the given example I would actually press `v ww ww ww c` (spaces only for legibility) or something like `f<some letter>...c`. I also did not get into plugins like sneak.vim.

---

What about plugins which define their own motions? Do they need to support visual.nvim explicitly? For example, VimTeX has defined many text objects and motions for LaTeX files:
- https://github.com/lervag/vimtex/blob/master/VISUALS.md#motion-commands
- https://github.com/lervag/vimtex/blob/master/VISUALS.md#text-objects)

**Comment by 00sapo** [comment]
Thanks, I will add it asap, or you could create a PR?

As regarding other plugins such as vimtex, treesitter-textobjects, etc, if they really create text objects, they will work. We are not changing anything to the inner mechanism of vim. What we are doing is command remapping. If they are based on command remapping, then they could misbehave if they conflict with our mappings. However, users can adapt the mappings as they like. What we can do is just provide snippets for easing the configurations...
